config/routes.rb
Preschool::Application.routes.draw do
  get "user/index"

  get "user/show"

  get "home/index"

  resources :course_history_tables

  resources :courses

  resources :instructors

  resources :classroom_logs

  resources :children

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users

end

app/models/classroom_log.rb
class ClassroomLog < ActiveRecord::Base
  attr_accessible :child_id, :classroom_number, :instructor_id

  belongs_to :child #for child name drop down
  belongs_to :instructor #for instructor name drop down
end

app/controllers/classroom_logs_controller.rb
class ClassroomLogsController < ApplicationController
  # GET /classroom_logs
  # GET /classroom_logs.json
  def index
    @classroom_logs = ClassroomLog.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @classroom_logs }
    end
  end

  # GET /classroom_logs/1
  # GET /classroom_logs/1.json
  def show
    @classroom_log = ClassroomLog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @classroom_log }
    end
  end

  # GET /classroom_logs/new
  # GET /classroom_logs/new.json
  def new
    @classroom_log = ClassroomLog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @classroom_log }
    end
  end

  # GET /classroom_logs/1/edit
  def edit
    @classroom_log = ClassroomLog.find(params[:id])
  end

  # POST /classroom_logs
  # POST /classroom_logs.json
  def create
    @classroom_log = ClassroomLog.new(params[:classroom_log])

    respond_to do |format|
      if @classroom_log.save
        format.html { redirect_to @classroom_log, notice: 'Classroom log was successfully created.' }
        format.json { render json: @classroom_log, status: :created, location: @classroom_log }
      else
        format.html { render action: "new" }
        format.json { render json: @classroom_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /classroom_logs/1
  # PUT /classroom_logs/1.json
  def update
    @classroom_log = ClassroomLog.find(params[:id])

    respond_to do |format|
      if @classroom_log.update_attributes(params[:classroom_log])
        format.html { redirect_to @classroom_log, notice: 'Classroom log was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @classroom_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classroom_logs/1
  # DELETE /classroom_logs/1.json
  def destroy
    @classroom_log = ClassroomLog.find(params[:id])
    @classroom_log.destroy

    respond_to do |format|
      format.html { redirect_to classroom_logs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/classroom_logs_helper.rb
module ClassroomLogsHelper
end

app/views/classroom_logs/_form.html.erb
<%= form_for(@classroom_log) do |f| %>
  <% if @classroom_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@classroom_log.errors.count, "error") %> prohibited this classroom_log from being saved:</h2>

      <ul>
      <% @classroom_log.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :child_id, "Select Child:"%><br />
    <%= f.select :child_id, Child.find(:all , :order => "child_fname, child_lname").collect {|c|
      [(c.child_fname + " " + c.child_lname), c.id]} %>
  </div>
  <div class="field">
    <%= f.label :instructor_id, "Select Instructor:" %><br />
    <%= f.select :instructor_id, Instructor.find(:all , :order => "instructor_fname, instructor_lname").collect {|i|
      [(i.instructor_fname + " " + i.instructor_lname), i.id]} %>
  </div>
  <div class="field">
    <%= f.label :classroom_number, "Select Classroom Number:" %><br />
    <%= f.select :classroom_number, [[101, '101'], [102, '102'], [103, '103'], [104, '104']] %>
  </div>
  <div class="actions">
    <%= f.submit "Submit New Classroom Assignment"%>
  </div>
<% end %>

app/views/classroom_logs/edit.html.erb
<h1>Edit Classroom Log</h1>

<%= render 'form' %>

<%= link_to 'Show', @classroom_log %> |
<%= link_to 'Back', classroom_logs_path %>

app/views/classroom_logs/index.html.erb
<h1>Classroom Log</h1>

<table>
  <tr>
    <th>Child Name</th>
    <th>Instructor Name</th>
    <th>Classroom Number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @classroom_logs.each do |classroom_log| %>
  <tr>
    <td><%= classroom_log.child.child_fname %><%= classroom_log.child.child_lname %></td>
    <td><%= classroom_log.instructor.instructor_fname %> <%= classroom_log.instructor.instructor_lname %></td>
    <td><%= classroom_log.classroom_number %></td>
    <td><%= link_to 'Show', classroom_log %></td>
    <td><%= link_to 'Edit', edit_classroom_log_path(classroom_log) %></td>
    <td><%= link_to 'Destroy', classroom_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Classroom Assignment', new_classroom_log_path %>

app/views/classroom_logs/new.html.erb
<h1>New Classroom Assignment</h1>

<%= render 'form' %>

<%= link_to 'Back', classroom_logs_path %>

app/views/classroom_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Child Name:</b>
  <%= @classroom_log.child.child_fname %> <%= @classroom_log.child.child_lname %>
</p>

<p>
  <b>Instructor Name:</b>
  <%= @classroom_log.instructor.instructor_fname %> <%= @classroom_log.instructor.instructor_lname %>
</p>

<p>
  <b>Classroom Number:</b>
  <%= @classroom_log.classroom_number %>
</p>


<%= link_to 'Edit', edit_classroom_log_path(@classroom_log) %> |
<%= link_to 'Back', classroom_logs_path %>