config/routes.rb
Preschool::Application.routes.draw do
  get "user/index"

  get "user/show"

  get "home/index"

  resources :course_history_tables

  resources :courses

  resources :instructors

  resources :classroom_logs

  resources :children

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users

end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  attr_accessible :instructor_email, :instructor_fname, :instructor_lname, :instructor_phone

  has_many :classroom_logs #for instructor name drop down in Classroom_log table
  has_many :course_history_tables #for instructor name drop down in Course_history table
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = Instructor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @instructors }
    end
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
    @instructor = Instructor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @instructor }
    end
  end

  # GET /instructors/new
  # GET /instructors/new.json
  def new
    @instructor = Instructor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @instructor }
    end
  end

  # GET /instructors/1/edit
  def edit
    @instructor = Instructor.find(params[:id])
  end

  # POST /instructors
  # POST /instructors.json
  def create
    @instructor = Instructor.new(params[:instructor])

    respond_to do |format|
      if @instructor.save
        format.html { redirect_to @instructor, notice: 'Instructor was successfully created.' }
        format.json { render json: @instructor, status: :created, location: @instructor }
      else
        format.html { render action: "new" }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /instructors/1
  # PUT /instructors/1.json
  def update
    @instructor = Instructor.find(params[:id])

    respond_to do |format|
      if @instructor.update_attributes(params[:instructor])
        format.html { redirect_to @instructor, notice: 'Instructor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor = Instructor.find(params[:id])
    @instructor.destroy

    respond_to do |format|
      format.html { redirect_to instructors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<%= form_for(@instructor) do |f| %>
  <% if @instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

      <ul>
      <% @instructor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :instructor_fname, "Enter First Name:" %><br />
    <%= f.text_field :instructor_fname %>
  </div>
  <div class="field">
    <%= f.label :instructor_lname, "Enter Last Name:" %><br />
    <%= f.text_field :instructor_lname %>
  </div>
  <div class="field">
    <%= f.label :instructor_email, "Enter E-mail:" %><br />
    <%= f.text_field :instructor_email %>
  </div>
  <div class="field">
    <%= f.label :instructor_phone, "Enter Phone:   (xxx)xxx-xxxx" %><br />
    <%= f.text_field :instructor_phone %>
  </div>
  <div class="actions">
    <%= f.submit "Submit New Instructor"%>
  </div>
<% end %>

app/views/instructors/edit.html.erb
<h1>Edit Instructor</h1>

<%= render 'form' %>

<%= link_to 'Show', @instructor %> |
<%= link_to 'Back', instructors_path %>

app/views/instructors/index.html.erb
<h1>Current Instructors</h1>

<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>E-mail</th>
    <th>Phone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @instructors.each do |instructor| %>
  <tr>
    <td><%= instructor.instructor_fname %></td>
    <td><%= instructor.instructor_lname %></td>
    <td><%= instructor.instructor_email %></td>
    <td><%= instructor.instructor_phone %></td>
    <td><%= link_to 'Show', instructor %></td>
    <td><%= link_to 'Edit', edit_instructor_path(instructor) %></td>
    <td><%= link_to 'Destroy', instructor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Instructor', new_instructor_path %>

app/views/instructors/new.html.erb
<h1>New Instructor</h1>

<%= render 'form' %>

<%= link_to 'Back', instructors_path %>

app/views/instructors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Instructor fname:</b>
  <%= @instructor.instructor_fname %>
</p>

<p>
  <b>Instructor lname:</b>
  <%= @instructor.instructor_lname %>
</p>

<p>
  <b>Instructor email:</b>
  <%= @instructor.instructor_email %>
</p>

<p>
  <b>Instructor phone:</b>
  <%= @instructor.instructor_phone %>
</p>


<%= link_to 'Edit', edit_instructor_path(@instructor) %> |
<%= link_to 'Back', instructors_path %>