config/routes.rb
Preschool::Application.routes.draw do
  get "user/index"

  get "user/show"

  get "home/index"

  resources :course_history_tables

  resources :courses

  resources :instructors

  resources :classroom_logs

  resources :children

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users

end

app/controllers/course_history_tables_controller.rb
class CourseHistoryTablesController < ApplicationController
  # GET /course_history_tables
  # GET /course_history_tables.json
  def index
    @course_history_tables = CourseHistoryTable.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @course_history_tables }
    end
  end

  # GET /course_history_tables/1
  # GET /course_history_tables/1.json
  def show
    @course_history_table = CourseHistoryTable.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course_history_table }
    end
  end

  # GET /course_history_tables/new
  # GET /course_history_tables/new.json
  def new
    @course_history_table = CourseHistoryTable.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course_history_table }
    end
  end

  # GET /course_history_tables/1/edit
  def edit
    @course_history_table = CourseHistoryTable.find(params[:id])
  end

  # POST /course_history_tables
  # POST /course_history_tables.json
  def create
    @course_history_table = CourseHistoryTable.new(params[:course_history_table])

    respond_to do |format|
      if @course_history_table.save
        format.html { redirect_to @course_history_table, notice: 'Course history table was successfully created.' }
        format.json { render json: @course_history_table, status: :created, location: @course_history_table }
      else
        format.html { render action: "new" }
        format.json { render json: @course_history_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /course_history_tables/1
  # PUT /course_history_tables/1.json
  def update
    @course_history_table = CourseHistoryTable.find(params[:id])

    respond_to do |format|
      if @course_history_table.update_attributes(params[:course_history_table])
        format.html { redirect_to @course_history_table, notice: 'Course history table was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @course_history_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /course_history_tables/1
  # DELETE /course_history_tables/1.json
  def destroy
    @course_history_table = CourseHistoryTable.find(params[:id])
    @course_history_table.destroy

    respond_to do |format|
      format.html { redirect_to course_history_tables_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/course_history_tables_helper.rb
module CourseHistoryTablesHelper
end

app/views/course_history_tables/_form.html.erb
<%= form_for(@course_history_table) do |f| %>
    <% if @course_history_table.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@course_history_table.errors.count, "error") %> prohibited this course_history_table from being saved:</h2>

          <ul>
            <% @course_history_table.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :instructor_id, "Select Instructor:" %><br />
      <%= f.select :instructor_id, Instructor.find(:all , :order => "instructor_fname, instructor_lname").collect {|i|
        [(i.instructor_fname + " " + i.instructor_lname), i.id]} %>
    </div>
    <div class="field">
      <%= f.label :course_id, "Select Course:" %><br />
      <%= f.select :course_id, Course.find(:all).collect {|c| [(c.course_name), c.id]} %>
    </div>
    <div class="field">
      <%= f.label :course_status, "Course Status:"%><br />
      <%= f.radio_button :course_status, 'Full' %> <%= f.label "course_full", "Full" %> <br />
      <%= f.radio_button :course_status, 'Open' %> <%= f.label "course_open", "Open" %> <br />
    </div>
    <div class="field">
      <%= f.label :child_id, "Select Age Group"%><br />
      <%= f.select :child_id, Child.find(:all).collect {|a| [(a.age_group), a.id]} %>
    </div>
    <div class="actions">
      <%= f.submit "Submit New Course History"%>
    </div>
<% end %>

app/views/course_history_tables/edit.html.erb
<h1>Edit Course History</h1>

<%= render 'form' %>

<%= link_to 'Show', @course_history_table %> |
<%= link_to 'Back', course_history_tables_path %>

app/views/course_history_tables/index.html.erb
<h1>Course History</h1>

<table>
  <tr>
    <th>Instructor Name</th>
    <th>Course Name</th>
    <th>Course Status</th>
    <th>Age Group</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @course_history_tables.each do |course_history_table| %>
      <tr>
        <td><%= course_history_table.instructor.instructor_fname %> <%= course_history_table.instructor.instructor_lname %></td>
        <td><%= course_history_table.course.course_name %></td>
        <td><%= course_history_table.course_status %></td>
        <td><%= course_history_table.child.age_group %></td>
        <td><%= link_to 'Show', course_history_table %></td>
        <td><%= link_to 'Edit', edit_course_history_table_path(course_history_table) %></td>
        <td><%= link_to 'Destroy', course_history_table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Course History', new_course_history_table_path %>

app/views/course_history_tables/new.html.erb
<h1>New Course History</h1>

<%= render 'form' %>

<%= link_to 'Back', course_history_tables_path %>

app/views/course_history_tables/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Instructor:</b>
  <%= @course_history_table.instructor.instructor_fname %> <%= @course_history_table.instructor.instructor_lname %>
</p>

<p>
  <b>Course:</b>
  <%= @course_history_table.course.course_name %>
</p>

<p>
  <b>Course Status:</b>
  <%= @course_history_table.course_status %>
</p>

<p>
  <b>Age Group:</b>
  <%= @course_history_table.child.age_group %>
</p>


<%= link_to 'Edit', edit_course_history_table_path(@course_history_table) %> |
<%= link_to 'Back', course_history_tables_path %>