config/routes.rb
Preschool::Application.routes.draw do
  get "user/index"

  get "user/show"

  get "home/index"

  resources :course_history_tables

  resources :courses

  resources :instructors

  resources :classroom_logs

  resources :children

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/new
  # GET /courses/new.json
  def new
    @course = Course.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(params[:course])

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render json: @course, status: :created, location: @course }
      else
        format.html { render action: "new" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.json
  def update
    @course = Course.find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :course_name, "Enter Course Name:"%><br />
    <%= f.text_field :course_name %>
  </div>
  <div class="field">
    <%= f.label :course_description, "Enter Course Description:" %><br />
    <%= f.text_field :course_description %>
  </div>
  <div class="actions">
    <%= f.submit "Submit New Course"%>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Edit Course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Current Courses</h1>

<table>
  <tr>
    <th>Course Name</th>
    <th>Course Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @courses.each do |course| %>
  <tr>
    <td><%= course.course_name %></td>
    <td><%= course.course_description %></td>
    <td><%= link_to 'Show', course %></td>
    <td><%= link_to 'Edit', edit_course_path(course) %></td>
    <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Course Name:</b>
  <%= @course.course_name %>
</p>

<p>
  <b>Course Description:</b>
  <%= @course.course_description %>
</p>


<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>